<div class="checkout-help-page">

  <div class="pane">
    <div class="header">
      <h2>Recurring Payments</h2>
    </div>
    <ul class="dotted">
      <li>Create a single (standalone) <a href="reference/merchant-api-reference/recurring-payments/payment-plans" target="_blank">Payment Plan</a></li>
      <li>Associate an existing <em class="">Payment Plan</em> with a <em class="">Charge</em> request to create a <a href="reference/merchant-api-reference/recurring-payments/customer-payment-plans/charge-with-existing-plan" target="_blank">Customer Payment Plan</a></li>
      <li>Create a <em class="">Payment Plan</em> and <em class="">Charge</em> request simultaneously to create a <a href="reference/merchant-api-reference/recurring-payments/customer-payment-plans/charge-with-new-plan" target="_blank">Customer Payment Plan</a></li>
    </ul>
  </div>
</div>